# Generated by Django 3.2.16 on 2022-12-05 19:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "Место", "verbose_name_plural": "Места"},
        ),
        migrations.AlterField(
            model_name="place",
            name="coord_lat",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
                verbose_name="Широта",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="coord_lng",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
                verbose_name="Долгота",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=models.TextField(verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=models.TextField(verbose_name="Краткое описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название места"),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_number", models.PositiveSmallIntegerField()),
                ("image", models.ImageField(upload_to="")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
    ]
