# Generated by Django 3.2.16 on 2022-12-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_auto_20221205_1957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, upload_to="places"),
        ),
    ]
