# Generated by Django 3.2.16 on 2022-12-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_alter_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image_number",
        ),
        migrations.AddField(
            model_name="image",
            name="position",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Позиция"),
        ),
        migrations.AddField(
            model_name="place",
            name="placeId",
            field=models.SlugField(default=1123),
            preserve_default=False,
        ),
    ]
