# Generated by Django 3.2.16 on 2022-12-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0010_auto_20221206_1348"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["placeId"],
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
    ]
