# Generated by Django 3.2.16 on 2022-12-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0011_alter_place_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["position"],
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
            },
        ),
    ]
