# Generated by Django 3.2.16 on 2022-12-09 08:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20221207_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='coord_lat',
            new_name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='coord_lng',
        ),
        migrations.AddField(
            model_name='place',
            name='langitude',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place'),
        ),
    ]
