# Generated by Django 3.2.16 on 2022-12-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20221209_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='langitude',
            new_name='longitude',
        ),
    ]
